services:
  - type: web
    name: telegram-userbot-controller
    runtime: node
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 